### ISSUE TITLE
Still Maintained?

### ISSUE THREAD

**Issue by vordimous** [igorbarinov/awesome-data-engineering#142]
@igorbarinov is this repo still being maintained or would it be better to fork it?

**Comment by JonathanLoscalzo** [comment]
Last change was 1 year ago, so perhaps not. ::(

**Comment by vordimous** [comment]
@igorbarinov, would you consider adding some more maintainers to help merge some PRs?

**Comment by vordimous** [comment]
@igorbarinov If you have abandoned this repo, I can fork this and start the process of transferring references and new PRs. If you don't want me to do this please respond soon.

**Comment by vordimous** [comment]
Thank you @igorbarinov

**Comment by Slach** [comment]
@igorbarinov @vordimous glad to see list still maintained in the old address not in fork

**Comment by vordimous** [comment]
Thank you @Slach, if you can help me get caught up with some of these PRs by reviewing any that stand out to you I would appreciate it! I will also be adding some more automated validation if it is possible.
