### ISSUE TITLE
Missing MarkLogic

### ISSUE THREAD

**Issue by damonfeldman** [igorbarinov/awesome-data-engineering#54]
Hi Igor. Consider adding MarkLogic as a document DB with RDF and text search all integrated (also geospatial). Security/enterprise focus.

 Summary:  http://www.zdnet.com/article/marklogic-9-launched-with-big-data-in-mind/ 

It runs Healthcare.gov, a bunch of banks, publishers, etc. Hundreds of clients, 15 years old.

**Comment by vordimous** [comment]
@damonfeldman thank you for the suggestion. If you think this should be added please create a PR.
