### ISSUE TITLE
Additions to TSDBs section

### ISSUE THREAD

**Issue by floer32** [igorbarinov/awesome-data-engineering#74]
* Timescale DB ( PostgreSQL extension )
* Epic spreadsheet comparing OSS timeseries options

I have notes/tabs on these (has been a big subject at work recently), I’ll submit a PR soon :-)

**Comment by igorbarinov** [comment]
Thanks, waiting for it.

**Comment by vordimous** [comment]
@floer32 thank you for the suggestion. If you think this should be added please create a PR.
